"""Advanced billing

Revision ID: 2f596ca1c1c3
Revises: f48d122b6034
Create Date: 2026-04-11 10:12:18.947588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f596ca1c1c3'
down_revision: Union[str, Sequence[str], None] = 'f48d122b6034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('current_storage_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('ingress_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('egress_bytes', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('internal_transfer_bytes', sa.Integer(), nullable=True))
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.INTEGER(), nullable=True))
    op.drop_column('buckets', 'internal_transfer_bytes')
    op.drop_column('buckets', 'egress_bytes')
    op.drop_column('buckets', 'ingress_bytes')
    op.drop_column('buckets', 'current_storage_bytes')
    # ### end Alembic commands ###
