"""API Request Billing

Revision ID: 832548efeb8a
Revises: 3a60929c86b3
Create Date: 2026-04-11 11:02:40.448414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832548efeb8a'
down_revision: Union[str, Sequence[str], None] = '3a60929c86b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('count_write_requests', sa.Integer(), nullable=True))
    op.add_column('buckets', sa.Column('count_read_requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'count_read_requests')
    op.drop_column('buckets', 'count_write_requests')
    # ### end Alembic commands ###
