"""added queued_messages

Revision ID: c573caff4ad5
Revises: 832548efeb8a
Create Date: 2026-04-16 09:04:05.094823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c573caff4ad5'
down_revision: Union[str, Sequence[str], None] = '832548efeb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queued_messages_is_delivered'), 'queued_messages', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_queued_messages_topic'), 'queued_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queued_messages_topic'), table_name='queued_messages')
    op.drop_index(op.f('ix_queued_messages_is_delivered'), table_name='queued_messages')
    op.drop_table('queued_messages')
    # ### end Alembic commands ###
