"""Added bandwidth_bytes

Revision ID: f48d122b6034
Revises: 2eeb8d2f24f1
Create Date: 2026-04-09 10:31:42.095823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48d122b6034'
down_revision: Union[str, Sequence[str], None] = '2eeb8d2f24f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###
